# Generated by Django 5.2.17 on 2026-09-12 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0002_verification_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='automated_result',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='card_ocr_date_of_birth',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='card_ocr_document_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='card_ocr_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='chip_date_of_birth',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='chip_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='identity_mismatch_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='notary_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='notary_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='notary_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentshield_notary_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rentshield_identity/videos/'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_notary_review', 'Awaiting Notary Public review'), ('verified', 'Verified'), ('failed', 'Failed'), ('manual_review', 'Needs manual review')], default='pending', max_length=32),
        ),
    ]
