# Generated by Django 5.2.17 on 2026-09-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0003_notary_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='chip_document_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
