# Generated by Django 5.2.17 on 2026-09-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0004_chip_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='chip_photo',
            field=models.FileField(blank=True, null=True, upload_to='rentshield_identity/chip_photos/'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='chip_selfie_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
