# Generated by Django 5.2.17 on 2026-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0005_chip_photo_face_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='ai_prescreen_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
