# Generated by Django 5.2.17 on 2026-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0007_devicepairingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='declared_can',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='declared_date_of_birth',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='declared_document_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='declared_document_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='declared_expiry_date',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
