# Generated by Django 5.2.17 on 2026-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0008_identityverification_declared_can_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='additional_id_photo',
            field=models.FileField(blank=True, null=True, upload_to='rentshield_identity/additional_ids/'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='additional_id_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
