# Generated by Django 5.2.17 on 2026-09-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0009_identityverification_additional_id_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='additional_id_photo',
        ),
        migrations.AddField(
            model_name='identityverification',
            name='additional_id_photo_back',
            field=models.FileField(blank=True, null=True, upload_to='rentshield_identity/additional_ids/'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='additional_id_photo_front',
            field=models.FileField(blank=True, null=True, upload_to='rentshield_identity/additional_ids/'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='additional_id_type',
            field=models.CharField(blank=True, choices=[('driving_licence', 'Driving Licence'), ('national_id', 'National ID Card'), ('residence_visa', 'Residence Visa'), ('second_passport', 'Second Passport'), ('other', 'Other ID document')], default='', max_length=32),
        ),
    ]
