# Generated by Django 5.2.17 on 2026-09-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0010_remove_identityverification_additional_id_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_notary_review', 'Awaiting Notary Public review'), ('verified', 'Verified'), ('failed', 'Failed'), ('manual_review', 'Needs manual review'), ('needs_more_info', 'Needs more from you')], default='pending', max_length=32),
        ),
    ]
