# Generated by Django 5.2.17 on 2026-09-14 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0011_alter_identityverification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerificationCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed -- waiting on the user'), ('confirmed', 'Confirmed'), ('reschedule_requested', 'User asked for a different time'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], default='proposed', max_length=32)),
                ('notary_call_notes', models.TextField(blank=True, default='')),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='rentshield_identity/call_recordings/')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='rentshield_identity.identityverification')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentshield_proposed_video_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
