# Generated by Django 5.2.17 on 2026-09-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0012_identityverificationcall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityverificationcall',
            options={'ordering': ['-created_at']},
        ),
    ]
