# Generated by Django 5.2.17 on 2026-09-14 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentshield_identity', '0013_alter_identityverificationcall_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentshield_claimed_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IdentityVerificationAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.PositiveIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('submitted_for_review', 'Submitted for Notary review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('requested_more_info', 'Sent back for more info'), ('reset', 'Reset (evidence wiped)'), ('deleted', 'Deleted'), ('call_scheduled', 'Video call scheduled'), ('call_confirmed', 'Video call confirmed'), ('call_reschedule_requested', 'Video call reschedule requested'), ('call_completed', 'Video call completed'), ('call_no_show', 'Video call no-show')], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentshield_verification_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
