# Generated by Django 5.2.17 on 2026-09-23 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_alter_rentshieldpermissionauditlog_actor'),
        ('rentshield_identity', '0014_identityverification_claimed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeSignerVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(blank=True, default='', max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('provider', models.CharField(default='idswyft', max_length=32)),
                ('verification_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('manual_review', 'Needs manual review')], default='pending', max_length=32)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='rentshield_identity/signer_passports/')),
                ('selfie_photo', models.FileField(blank=True, null=True, upload_to='rentshield_identity/signer_selfies/')),
                ('ocr_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('name_mismatch', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rentshield_signer_verification', to='documents.document')),
            ],
        ),
    ]
