# Generated by Django 5.2.17 on 2026-09-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0025_workflowaction_apply_ai_suggestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("landlord_name", models.CharField(max_length=255)),
                (
                    "landlord_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("tenant_name", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Apartment", "Apartment"),
                            ("Villa", "Villa"),
                            ("Townhouse", "Townhouse"),
                            ("Office", "Office"),
                            ("Retail", "Retail"),
                        ],
                        default="Apartment",
                        max_length=32,
                    ),
                ),
                ("unit_no", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "building_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plot_number", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "ejari_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("notice_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale of Property"),
                            ("personal", "Personal Use / Recovery"),
                            ("demolition", "Demolition"),
                            ("renovation", "Extensive Renovation"),
                            ("nonpayment", "Non-payment of Rent"),
                            ("sublease", "Unauthorized Subleasing"),
                        ],
                        max_length=32,
                    ),
                ),
                ("add_notarization", models.BooleanField(default=False)),
                ("add_ai_review", models.BooleanField(default=False)),
                (
                    "consume_task_id",
                    models.CharField(blank=True, max_length=72, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rentshield_notices",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
