# Generated by Django 5.2.17 on 2026-09-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentshield", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="esign_external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="esign_provider",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="esign_signed_document_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="esign_signing_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="esign_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
