# Assembles a filing-packet cover sheet for Dubai's Rental Dispute
# Settlement Centre (RDC/RDSC) online portal (rdc.gov.ae) once a notice
# has been served and the tenant hasn't complied -- NOT an RDC API
# integration (no public API exists) and NOT the RDC claim form itself
# (that's filed directly at rdc.gov.ae). This just tells the landlord
# exactly what that portal will ask for and whether RentShield already
# has it linked, so they aren't hunting for documents from scratch.
from __future__ import annotations

import html as html_module

from documents.rentshield.constants import ALL_REASONS
from documents.rentshield.pdf import render_html_to_pdf
from documents.rentshield.service_methods import SERVICE_METHODS

# RDC's own published fee rule (3.5% of annual rent, min AED 500, max AED
# 20,000) -- stated as reference, never computed: RentShield has no field
# for the actual annual rent amount, and inventing one just for a fee
# estimate here would be scope this feature doesn't need.
_RDC_FEE_NOTE = "RDC's filing fee is 3.5% of the annual rent (minimum AED 500, maximum AED 20,000), payable when you file."


def _esc(value) -> str:
    return html_module.escape(str(value) if value is not None else "")


def _checklist_row(label: str, present: bool, note: str = "") -> str:
    mark = "&#10003;" if present else "&#9633;"
    status_class = "rs-present" if present else "rs-missing"
    detail = f" -- {_esc(note)}" if note else ""
    return f'<li class="{status_class}"><span class="rs-mark">{mark}</span> {_esc(label)}{detail}</li>'


def render_rdsc_packet_html(fields: dict) -> str:
    reason_meta = ALL_REASONS.get(fields.get("reason"))
    reason_label = reason_meta["label"] if reason_meta else fields.get("reason")

    service_method_key = fields.get("service_method")
    service_method_label = (
        SERVICE_METHODS[service_method_key]["label"]
        if service_method_key in SERVICE_METHODS
        else None
    )

    checklist = "\n".join(
        [
            _checklist_row(
                "Ejari certificate",
                bool(fields.get("ejari_certificate_document")),
                f"Ejari No. {fields['ejari_number']}" if fields.get("ejari_number") else "not linked on this notice yet",
            ),
            _checklist_row(
                "Tenancy contract",
                bool(fields.get("tenancy_contract_document")),
                "" if fields.get("tenancy_contract_document") else "not linked on this notice yet",
            ),
            _checklist_row(
                "This notice itself",
                True,
                "generated and stored by RentShield",
            ),
            _checklist_row(
                "Proof of service",
                bool(fields.get("service_evidence_document")) or service_method_key == "notary_public",
                service_method_label or "no service method recorded yet",
            ),
        ],
    )

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Times New Roman', serif; color: #1a1a1a; line-height: 1.6; padding: 40px; }}
  .kicker {{ text-transform: uppercase; letter-spacing: 0.08em; font-size: 11px; color: #666; }}
  h1 {{ font-size: 22px; margin: 4px 0; }}
  .meta {{ margin: 16px 0; font-size: 13px; }}
  .meta td {{ padding: 2px 12px 2px 0; }}
  ul.rs-checklist {{ list-style: none; padding: 0; font-size: 13px; }}
  ul.rs-checklist li {{ padding: 4px 0; }}
  .rs-mark {{ display: inline-block; width: 1.4em; }}
  .rs-present {{ color: #0a7a3d; }}
  .rs-missing {{ color: #b23b1f; }}
  .footer {{ font-size: 11px; color: #666; margin-top: 24px; }}
</style>
</head>
<body>
  <p class="kicker">RDSC Filing Packet -- Reference Checklist</p>
  <h1>{_esc(reason_label)} &mdash; {_esc(fields.get("tenant_name"))}</h1>
  <table class="meta">
    <tr><td>Landlord</td><td>{_esc(fields.get("landlord_name"))}</td></tr>
    <tr><td>Ejari No.</td><td>{_esc(fields.get("ejari_number") or "not recorded")}</td></tr>
    <tr><td>Notice Date</td><td>{_esc(fields.get("notice_date"))}</td></tr>
    <tr><td>Notice Period</td><td>{_esc(fields.get("notice_period_days"))} days</td></tr>
    <tr><td>Served Date</td><td>{_esc(fields.get("served_date") or "not recorded")}</td></tr>
    <tr><td>Service Method</td><td>{_esc(service_method_label or "not recorded")}</td></tr>
  </table>
  <p>What Dubai's Rental Dispute Settlement Centre online portal (rdc.gov.ae) asks for, and whether it's linked on this notice today:</p>
  <ul class="rs-checklist">{checklist}</ul>
  <p>{_esc(_RDC_FEE_NOTE)}</p>
  <p class="footer">This is a reference checklist generated by RentShield, not a court filing and not submitted to RDC on your behalf -- file directly at rdc.gov.ae using the documents above.</p>
</body>
</html>"""


def build_rdsc_packet(fields: dict) -> bytes:
    return render_html_to_pdf(render_rdsc_packet_html(fields))
