# Generated by Django 5.2.17 on 2026-09-09 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(help_text='Notice-creation payload this order is for.')),
                ('amount_aed', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('demo_paid', 'Paid (demo)'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentshield_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
